tables:
    pgbench_accounts:
        main_table: pgbench_accounts
        buffer_table: pgbench_accounts_buf # optional, if not specified, insert directly to the main table
        buffer_row_id: 'row_id' # column name in the buffer table to store row id
        engine: CollapsingMergeTree
        buffer_size: 1000
        merge_threshold: 4 # buffers
        columns: # in the exact same order as in the pg table
            - aid:
                type: Int32
                name: aid
            - bid:
                type: Int32
                name: bid
            - abalance:
                type: Int32
                name: abalance
                empty_value: '0' # used for ReplacingMergeTree engine to discard old value
            - filler:
        sign_column: sign
        ver_column: ver
    pgbench_history:
        skip_init_sync: true
        main_table: pgbench_history
        engine: MergeTree
        columns:
            - tid:
                type: Int32
                name: tid
            - bid:
                type: Int32
                name: bid
            - aid:
                type: Int32
                name: aid
            - delta:
                type: Int32
                name: delta
            - mtime:
                type: DateTime
                name: mtime
            - filler:

lsnStateFilepath: state.yaml
inactivity_merge_timeout: '10s' # merge buffered data after that timeout
clickhouse: tcp://localhost:9000
pg:
    host: localhost
    port: 5432
    database: pg2ch
    user: postgres
    replication_slot_name: myslot
    publication_name: my_pub
